theme: jekyll-theme-minimal
logo: /docs/assets/Good-PhotoRoom.png
title: David Rodriguez
description: Mathematics | Artificial Intelligence
link: https://www.linkedin.com/in/david-rodr%C3%ADguez-2bab9b1b9/
